abbr 1 prevd
abbr 2 nextd
abbr :q exit
abbr :v vim
abbr asdfpa 'asdf plugin-add'
abbr asdfpl 'asdf plugin-list'
abbr asdfpr 'asdf plugin-remove'
abbr asdfup 'asdf plugin-update'
abbr asdfupa 'asdf plugin-update --all'
abbr asdfi 'asdf install'
abbr asdfc 'asdf current'
abbr asdfu 'asdf uninstall'
abbr asdfl 'asdf list'
abbr asdfla 'asdf list-all'
abbr bandle 'bundle install --jobs=5 --path=vendor/bundle'
abbr be 'bundle exec'
abbr bs 'brew services'
abbr bi 'brew install'
abbr cl clear
abbr g git
abbr g. 'git add .'
abbr ga 'git add'
abbr gaa 'git add --all'
abbr gacm 'git add --all .; and git commit -m'
abbr gcm 'git commit -m'
abbr gcam 'git commit --amend -m'
abbr gco 'git checkout'
abbr gcob 'git checkout -b'
abbr gcp 'git cherry-pick'
abbr gd 'git diff'
abbr grst 'git reset'
abbr gfrh 'git fetch; and git reset --hard'
abbr gfrb 'git fetch; and git rebase'
abbr gst 'git status'
abbr gp 'git push'
abbr gpf 'git push --force'
abbr gpr 'git pull --rebase'
abbr gr 'git rebase'
abbr gl 'git log'
abbr ixp 'iex -S mix phoenix.server'
abbr ixs 'iex -S mix'
abbr l ls
abbr m mix
abbr mt 'mix test'
abbr n npm
abbr nids 'npm install --save-dev --save-exact'
abbr nis 'npm install --save --save-exact'
abbr nr 'npm run'
abbr nt 'npm test'
abbr psaux 'ps aux'
abbr psgrep 'ps aux | grep'
abbr srestart 'brew services restart'
abbr sstart 'brew services start'
abbr sstop 'brew services stop'
abbr ta 'tmux attach; or tmux'
abbr y yarn
abbr ya 'yarn add --exact'
abbr yad 'yarn add --exact --dev'
abbr yr 'yarn run'
